services:
  mongodb:
    image: mongo:7
    # platform: "linux/amd64"
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    command: ["mongod", "--config", "/etc/mongod.conf"]
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - ./mongod.conf:/etc/mongod.conf:ro

networks:
  mongodb:
